language: python
python:
  - "3.8"

install:
  - pip install -r homework/requirements.txt

# command to run tests
script:
  - cd homework
  - coverage run --source=./test -m unittest discover -s test
  - coverage report -m
