language: python
python:
  - "3.8"

install:
  - pip install requests

# command to run tests
script:
  - cd homework
  - python -m unittest hw04_test
  - cd hw02a
  - python -m unittest TestTriangle
